### ISSUE TITLE
Unable to find a medium containing a live file system

### ISSUE THREAD

**Issue by freelock** [cawilliamson/ansible-gpdpocket#68]
Just like #19 , I'm getting this message after trying to boot from an ISO. I've tried the linked 16.04.3 image, 17.04 Ubuntu, 17.04 Ubuntu Mate, all build fine with the bootstrap-iso.sh script. I then used dd to create the image, and it loads up the grub screen and a splash screen for a minute or two, and then it stops with this error.

Is there a regression in the package? Some Bios setting I'm missing?

**Comment by icebal** [comment]
going to piggy back off you, since i replied to the old thread. original comment below:
I am also getting this with the 17.04 full desktop image and the latest git pull. This is happening in both the live boot entry, as well as just the installer entry

**Comment by snazzybunny** [comment]
same thing happens to me with 16.04.3 ubuntu and the new iso file is 6.5 gb

**Comment by icebal** [comment]
It seems like the ansible scripts are unpacking the squashfs, adding and changing, and then packaging both the new squashfs and the unpacked one

**Comment by cawilliamson** [comment]
I'll test this shortly - I do need to run a reinstall on my GPD Pocket anyway so it's a great time to test it.

**Comment by enthusi** [comment]
Same issue here.
Creating the ISO with an Ubuntu 17.04 system (the current one) based on both, 
the 17.04 and the 16.04.3 ISO images. Both fail to boot (either live or straight installer) with the message:
"Unable to find a medium containing a live file system".
Could anyone just host _A_ working Ubuntu image to at least have the GPD started?

**Comment by cawilliamson** [comment]
I believe this issue is now resolved due to the fix above.

Could someone please test and confirm this? :)

Thanks!

**Comment by enthusi** [comment]
I just tested it on 17.04 again and the issue remains.
But apparently at a later stage than before.
Again for both, live-Ubuntu and Installer. Can I provide anything that would help?
Last message (for starting the installer) is: 
Begin: Running /scripts/init-premount ...

BusyBox v1.22 BLABLA
Enter 'help' BLABLA

(initramfs) Unable to find a medium containing live system

**Comment by nexus511** [comment]
Just tested the last commit. Still does not work for (x)ubuntu-16.04 iso.

I have actually seen this issue while I have been working on iso customization in the past. I wish I could remember what I did to resolve it back then.

**Comment by cawilliamson** [comment]
@nexus511 I haven't been able to reproduce this using VMWare is the strange thing. I am about to try a 17.04 but I have been using a 16.04.3 image and it is booting without any problem whatsoever.

Are you certain you're not using a netinst image? This is a full -desktop image, right?

**Comment by seaplusplus** [comment]
I just tried 17.04. Same issue as enthusi. 

I used ubuntu-17.04-desktop-amd64.iso

**Comment by nexus511** [comment]
@cawilliamson Yey, it is not a netinst image. Do you have a link to the exact image you are using?

On my initramfs shell I am not able to see the USB-stick as /dev/sd*, while it has clearly been detected by the kernel as stated in dmesg.

**Comment by enthusi** [comment]
I just tried the latest checkout with an Ubuntu16.04.3 image (on an ubuntu17 system) with USB2 stick.
Same issue as I stated before.

**Comment by nexus511** [comment]
Okay. I tried it again and the issue remains.

I downloaded exactly this file here: http://releases.ubuntu.com/16.04/ubuntu-16.04.3-desktop-amd64.iso

```
# sha256sum ubuntu-16.04.3-desktop-amd64.iso ; md5sum ubuntu-16.04.3-desktop-amd64.iso 
1384ac8f2c2a6479ba2a9cbe90a585618834560c477a699a4a7ebe7b5345ddc1  ubuntu-16.04.3-desktop-amd64.iso
0d9fe8e1ea408a5895cbbe3431989295  ubuntu-16.04.3-desktop-amd64.iso
```

I used `ddrescue --force bootstrap.iso /dev/sdd ; sync` to get the image on my USB-stick. The system boots, the ubuntu bootscreen comes up and it stops working jumping into the init shell.

`dmesg` is telling me that it has detected my USB stick but I don't see any device-node in /dev. I don't see a message in `dmesg` that detects the stick as usb blockdevice. I am missing something like this:
```
[2353584.895858] usb-storage 1-5.2:1.0: USB Mass Storage device detected
[2353584.896973] scsi host21: usb-storage 1-5.2:1.0
[2353585.899416] scsi 21:0:0:0: Direct-Access     SanDisk  Ultra USB 3.0    1.00 PQ: 0 ANSI: 6
[2353585.900048] sd 21:0:0:0: Attached scsi generic sg2 type 0
[2353585.900450] sd 21:0:0:0: [sdd] 60062500 512-byte logical blocks: (30.8 GB/28.6 GiB)
[2353585.901108] sd 21:0:0:0: [sdd] Write Protect is off
[2353585.901111] sd 21:0:0:0: [sdd] Mode Sense: 43 00 00 00
[2353585.901413] sd 21:0:0:0: [sdd] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
```

So I would guess that the initrd or the kernel currently lacks support for USB block devices and thus is unable to detect the source partition properly.

**Comment by cawilliamson** [comment]
You may want to try again now - looks like the search pattern I had for finding initrd didn't include *.lz which is now what Ubuntu uses in 17.04 - it now does support this and should boot properly.

Let me know how it goes. :)

**Comment by seaplusplus** [comment]
I (an others) also had the issue with ubuntu-16.04.3-desktop-amd64.iso

I am trying it now, will report back. 

Thanks

**Comment by cawilliamson** [comment]
^ I've just made another small change - may be worth pulling that before building your ISO.

As for issues with 16.04.3 - I have been testing my images on VMWare booting in EFI mode so I guess that wouldn't need USB to boot - probably explains it. Sorry about that! (I got tired of rebuilding my GPD Pocket - I've only got one and it's my main one! :/)

**Comment by nexus511** [comment]
Still does not work for me on building ubuntu 16.04.3. I still get the old modules in the initrd-file on the stick:

```
$ lzcat ../initrd.lz | cpio -i
229382 blocks
$ ls lib/modules/
4.10.0-28-generic
```

**Comment by cawilliamson** [comment]
The thing is - Ansible isn't just a wrapper around bash commands so whilst you can enable verbose mode - it will typically not tell you a whole lot since unless you're using "shell" module stuff - it will use things like Python modules, etc. to achieve what it needs to achieve.

That having been said - I have tested this on my side and I do see 4.13.0-rc0 in /lib/modules/ on the Ubuntu 17.04 desktop livecd.

I'll confirm with 16.04 now - can't keep track here! >_<

**Comment by cawilliamson** [comment]
@nexus511 Just to confirm - you did download the latest version of the playbook before attempting to bootstrap the ISO again, right?

Daft question I know but it's very strange that you're not seeing any change in your resulting image despite two large changes to the code.

**Comment by cawilliamson** [comment]
Confirmed - I now have 16.04.3 running *with* the -rc0 bootstrap kernel along with -rc0 bootstrap modules.

**Comment by enthusi** [comment]
So 17.4 is working now?
Would your code/scripts fully run on an ARM architecture/Ubuntu? I won't have access to AMD64 until Monday probably. Is it feasible to upload the GPD image somewhere? :)

**Comment by nexus511** [comment]
@cawilliamson Yes, I have of course updated. I have even spawned and installed a completely new build-system and I am still stuck with a kernel version 4.13.0-rc0 and the original kernel modules as provided within the original system.

That might sound strange but for me this looks a bit like all things on the system stay the same except the kernel image getting changed against a new one. So something does not work here at all. I try to use another Ubuntu version as build host now. Maybe the problem is somehow related to the host and not the playbook.

**Comment by cawilliamson** [comment]
@enthusi It is for me, yep! It wont build on an ARM architecture but I'll certainly upload an ISO for you and you can DD it on ARM no problem! 👍 

Will update you shortly once it's uploaded. :)

**Comment by cawilliamson** [comment]
@nexus511 Firstly - what host distro are you using?

Secondly - could you run the ansible playbooks and provide me with full logging output?

You can do that by installing the package `pastebinit` and then running:

`bash bootstrap-iso.sh FILENAME | pastebinit`

Then just provide me the URL here and I'll read through the logs. 👍

**Comment by cawilliamson** [comment]
@enthusi https://drive.google.com/file/d/0B-UkhldACwrrdmFaOFdrcGhsRzQ/view?usp=sharing :)

**Comment by nexus511** [comment]
@cawilliamson I have tried the following distros:
- xubuntu 16.04 desktop amd64 clean setup from CD and updated to latest packages
- ubuntu 17.04 desktop amd64 clean setup from CD and updated to latest packages

Additional packages that I have installed are git and openssh-server, nothing else. The host is running in KVM has about 64GB of SSD, 32GB RAM and 6 cores to build.

As target systems I have tried
- xubuntu 16.04 on host xubuntu 16.04
- ubuntu 16.04.3 on host xubuntu 16.04
- ubuntu 17.04 on host ubuntu 17.04

Git clone location is /root/ansible-gpdpocket. I now started
```
bash ./bootstrap-iso.sh ubuntu-17.04-desktop-amd64.iso | pastebinit
```

The log has been placed here: http://paste.ubuntu.com/25341920/

**Comment by enthusi** [comment]
Thanks alot! Highly appreciated and I hopefully can contribute/help in the future.
Best wishes! (downloading it will take a while)

**Comment by cawilliamson** [comment]
@nexus511 Can you update and try again now? Believe I've found the problem.

@enthusi No problem but abandon download - I need to upload a new build with the fix above. :)

**Comment by nexus511** [comment]
Still. Original initrd.lz on the ubuntu live-CD:

```
# md5sum tmp/initrd.lz 
0ec39602f93b469bac13da9d31dfe7b6  tmp/initrd.lz
```

Version on bootstrap.iso:

```
# md5sum /mnt/casper/initrd.lz 
0ec39602f93b469bac13da9d31dfe7b6  /mnt/casper/initrd.lz
```

**Comment by enthusi** [comment]
Oh, ok. Thanks :-) I will check first thing in the morning.

**Comment by cawilliamson** [comment]
@nexus511 I've just downloaded the image and it booted flawlessly for me - yes on the GPD Pocket.

You're not using the USB-C port or a hub are you? I'm really not sure what's going on here or maybe you're using a funky image to build from. I'm using:

`18cc54af55d7ca931bbb8588e8d9c1bd  ubuntu-17.04-desktop-amd64.iso`

**Comment by seaplusplus** [comment]
I just tried again with fresh clone and 18cc54af55d7ca931bbb8588e8d9c1bd  ubuntu-17.04-desktop-amd64.iso

"Unable to find medium with containing a live file system"  after booting. 

Can you upload your bootstrap.iso?

**Comment by rdbell** [comment]
I'm having the same issue with 18cc54af55d7ca931bbb8588e8d9c1bd  ubuntu-17.04-desktop-amd64.iso

If someone could upload a working bootstrap.iso for 17.04 that would be great.

**Comment by enthusi** [comment]
Update. The image you linked to a few comments above boots well into the live Ubuntu 17.
You mentioned it missing a fix?
The screen is still oriented horizontally. Is that supposed to be the case? Thanks for all this :)

**Comment by nexus511** [comment]
@cawilliamson Yes I am using the same image as you do.

```
$ md5sum ubuntu-17.04-desktop-amd64.iso 
18cc54af55d7ca931bbb8588e8d9c1bd  ubuntu-17.04-desktop-amd64.iso
```

And yes I am sure that I am using the right USB port as the image you provided above boots on my GPD and I have had installed xubuntu/ubuntu without all the patches on the same port successfully before.

I am pretty shure that its just related to the task `- name: copy system initrd to iso (install)` or `- name: copy system initrd to iso (standard)`. It is not related to the pattern for initrd-filters that you habe been changing all along.

I am taking a look at it myself (i just forked your repo yesterday) and try to come up with a pull request as soon I understand whats going wrong there.

**Comment by nexus511** [comment]
Okay. The problem is that on ubuntu systems /bin/sh always points on /bin/dash and not /bin/bash by default. Ansible uses pythons proc_exec to issue "shell" tasks. Those tasks will always run as /bin/sh disregarding user settings for a shell, the executable configuration in ansible.cfg or the executing shell.

To ensure that commands that require bash-syntax are run as bash, it has explicitly be stated. An other option would be to change /bin/sh pointing on /bin/bash (which would be more a hack than a solution).

I sent in a pull request fixing the issue in a few minutes.

**Comment by cawilliamson** [comment]
I've now patched in the same fix for all instances of shell which should avoid any future issues related to shells. Thanks for this @nexus511 - saved me a lot of headache here. 👍 

Since this now looks to be resolved I'm going to close the ticket.

**Comment by enthusi** [comment]
Ubuntu 17.04 works for me now. Thanks alot!
