### ISSUE TITLE
bootstrap-iso script fails at git clone step

### ISSUE THREAD

**Issue by brittAnderson** [cawilliamson/ansible-gpdpocket#9]
Tried to run the bootstrap-iso script but fails at the git clone stage with error that /usr/src/ansible-gpdpocket ... directory already exists. I think you create this earlier in the bootstrap iso script and then the bootstrap-shell.sh is trying to create it anew when it wants to clone. Just a guess.

**Comment by cawilliamson** [comment]
When did you checkout the code?

This was an issue before but it should now be resolved as of yesterday.

**Comment by brittAnderson** [comment]
Within the last hour.

**Comment by cawilliamson** [comment]
Could you try again now?

Just added a fix which should fix this issue.

**Comment by diandengs** [comment]
Two hours ago，I downloaded https://github.com/cawilliamson/ansible-gpdpocket/archive/master.zip,
I use: bash bootstrap-iso.sh ubuntu-16.04.2-desktop-amd64.iso,encountered the same error, then I deleted ansible-gpdpocket, use git clone https://github.com/cawilliamson/ansible-gpdpocket.git to re-download, did not continue to report this error , But it reported a new mistake:

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Unexpected Exception: [Errno 38] Function not implemented
to see the full traceback, use -vvv

**Comment by cawilliamson** [comment]
Could you try now?

The only thing I can think of is perhaps you still have devices mounted at /var/tmp/bootstrap-iso and the new script should attempt to clean those up.

I'm not able to reproduce the Errno 38 stuff you're seeing at my end at all.

**Comment by diandengs** [comment]
I just retried a bit :bash bootstrap-iso.sh ubuntu-16.04.2-desktop-amd64.iso, or reported the same mistake, then, how can I operate? I tried to delete the folder：/var/tmp/bootstrap-iso, but the device was busy and could not be deleted

**Comment by brittAnderson** [comment]
Got fresh version with: `wget https://github.com/cawilliamson/ansible-gpdpocket/archive/master.zip
`

Just reran
`sudo bash ./bootstrap-iso.sh ../xubuntu-16.04.3-desktop-amd64.iso 
`
Got:
`Setting up git (1:2.7.4-0ubuntu1.1) ...
+ '[' -d /usr/src/ansible-gpdpocket/.git ']'
+ git clone https://github.com/cawilliamson/ansible-gpdpocket.git /usr/src/ansible-gpdpocket
fatal: destination path '/usr/src/ansible-gpdpocket' already exists and is not an empty directory.`

Is it possible you fixed it in the git version, but did not rezip it up for the instructions you have on redditt?

**Comment by cawilliamson** [comment]
I've figured out what the problem is and added a fix - sorry!

This should work properly now.

**Comment by cawilliamson** [comment]
(you'll need to redownload the fresh version)

It's because GitHub removes the ".git" folder in a downloaded repo (by ZIP) so you can't update that repo.  Oops!

**Comment by brittAnderson** [comment]
Redownloaded zip, expanded, reran bash command and got: 

`+ chroot /var/tmp/bootstrap-iso/squashfs /bin/bash -c '/bin/bash /tmp/bootstrap-system.sh'
/bin/bash: /tmp/bootstrap-system.sh: No such file or directory
`

Do I need to somehow "clean" from the earlier failures?

**Comment by cawilliamson** [comment]
Nope - I just need to clean my brain I think!

Fixed - was copying the file to /tmp/ instead of ${TMPDIR}/squashfs/tmp/ - looks like it's fixed in my testing now. Sorry about that!

**Comment by cawilliamson** [comment]
I can not believe this - think I'll grab a coffee!

Path was STILL broken - I've fixed this for real now. :|

Apologies for the inconvenience.

**Comment by diandengs** [comment]
I restart the computer after the successful removal of the folder:/var/tmp/bootstrap-iso/
Reappear：bash bootstrap-iso.sh ubuntu-16.04.2-desktop-amd64.iso
Still the same mistake：
c590953 added fix for bootstrap-system.sh copying
+ ANSIBLE_NOCOWS=1
+ ansible-playbook site.yml -e bootstrap=true
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Unexpected Exception: [Errno 38] Function not implemented
to see the full traceback, use -vvv


How to solve this problem?

**Comment by cawilliamson** [comment]
^ See above - this is now fixed (just tested)

**Comment by cawilliamson** [comment]
Let me test on the xubuntu iso though - maybe it has a quirk I'm not aware of.

**Comment by cawilliamson** [comment]
Works fine for me but I've just remembered where I've seen errno 38 - are you running on a 32 bit Linux install?

You will need to run on a 64bit system with a 64bit install of Linux in order to use my scripts.

**Comment by diandengs** [comment]
I'm a 64-bit system：
root@openmediavault:~# uname -a
Linux openmediavault 3.2.0-4-amd64 #1 SMP Debian 3.2.78-1 x86_64 GNU/Linux

**Comment by cawilliamson** [comment]
I've added `/dev/shm` mounting now - could you try again and let me know the output?

It's very strange that you're seeing this error but I'm not at my end with the same command.

**Comment by brittAnderson** [comment]
Current version works now. Closes my part of the issue. Thanks for all your work on this project.

**Comment by cawilliamson** [comment]
I'll close this one for now - feel free to re-open or create another issue diandengs.

**Comment by diandengs** [comment]
Sorry, I did not have time to retry last night, I just tried to build, or reported the same mistakes

**Comment by cawilliamson** [comment]
@diandengs Since I'm not able to reproduce this issue - I suggest you try on another host. You are running an extremely old version of debian and the linux kernel - it's entirely possible this is a bug elsewhere.

**Comment by diandengs** [comment]
I am upgrading my operating system, after the upgrade I try to look at the next

**Comment by diandengs** [comment]
Sorry for your misunderstood，I want to explain the issue 23 mentioned before，gpd-update that I understood is not Compiling and updating the whole system，However，It should be Just updating the drivers or patching the system kernel ！ In my opinion， the command gpd-upgrade should be better to compile the whole system！ Could you please add a command to just patch the current system.

**Comment by cawilliamson** [comment]
@diandengs I do understand your request - I didn't misunderstand. I just disagree with your opinion. The point of gpd-update is that it updates EVERYTHING it can. If you don't wish for this to happen you can simply never run it and stick with the bootstrap kernel.

I am not going to make changes to `gpd-update` to remove the kernel building functionality and have added a change to README.md to make it clear what happens when you run the `gpd-update` script.

Please do not hijack other tickets to make additional points about a closed ticket.
